FLASH-X: nameValueLL_data Module Reference
nameValueLL_data Module Reference
Data Types
type context_type
type int_list_type
type log_list_type
interface nameValueLL_add
interface nameValueLL_check
interface nameValueLL_find
interface nameValueLL_getType
interface nameValueLL_initContext
type real_list_type
type str_list_type
Functions/Subroutines
subroutine initContext (context)
subroutine getType (context, name, name_type)
subroutine nameValueLL_findReal (context, name, result)
subroutine nameValueLL_findInt (context, name, result)
subroutine nameValueLL_findStr (context, name, result)
subroutine nameValueLL_findLog (context, name, result)
subroutine nameValueLL_addReal (context, name, value, state)
subroutine nameValueLL_addInt (context, name, value, state)
subroutine nameValueLL_addStr (context, name, value, state)
subroutine nameValueLL_addLog (context, name, value, state)
subroutine nameValueLL_checkReal (node, value, valid)
subroutine nameValueLL_checkInt (node, value, valid)
subroutine nameValueLL_checkStr (node, value, valid)
Variables
integer, parameter NUM_MAX_RULES = 10
integer, parameter name_real = 1
integer, parameter name_int = 2
integer, parameter name_str = 3
integer, parameter name_log = 4
integer, parameter name_invalid = 0
integer, parameter TYPE_CONST = 0
integer, parameter TYPE_VAR = 1
integer, save num_params = 0
Detailed Description
Utility module that creates a linked list to hold runtime parameters and scalars
Arguments none
Function/Subroutine Documentation
getType()
subroutine nameValueLL_data::getType (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer, intent(out) name_type)
Given the name in a linked list and a context to search, find the type (real, integer, etc.) of the parameter. If the parameter is not found, return a value which indicates that the parameter is invalid.
context: name of context name: name (in) name_type: type of parameter (out)
Definition at line 162 of file nameValueLL_data.F90.
Referenced by nameValueLL_data::nameValueLL_add::nameValueLL_addInt(), nameValueLL_data::nameValueLL_add::nameValueLL_addLog(), nameValueLL_data::nameValueLL_add::nameValueLL_addReal(), and nameValueLL_data::nameValueLL_add::nameValueLL_addStr().
initContext()
subroutine nameValueLL_data::initContext (type (context_type), intent(out) context)
Make sure the context is in a defined initial state.
context: name of context
Definition at line 133 of file nameValueLL_data.F90.
nameValueLL_addInt()
subroutine nameValueLL_data::nameValueLL_addInt (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer, intent(in) value, integer, intent(in) state)
Definition at line 361 of file nameValueLL_data.F90.
Referenced by nameValueLL_setInt().
nameValueLL_addLog()
subroutine nameValueLL_data::nameValueLL_addLog (type (context_type), intent(inout) context, character(len=*), intent(in) name, logical, intent(in) value, integer, intent(in) state)
Definition at line 474 of file nameValueLL_data.F90.
Referenced by nameValueLL_setLog().
nameValueLL_addReal()
subroutine nameValueLL_data::nameValueLL_addReal (type (context_type), intent(inout) context, character(len=*), intent(in) name, real, intent(in) value, integer, intent(in) state)
Adds parameters to a linked list context implemented under the hood. This is an overloaded subroutine. It implements nameValueLL_addReal, nameValueLL_addInt, nameValueLL_addStr, nameValueLL_addLog
name: name value: name value
Definition at line 302 of file nameValueLL_data.F90.
Referenced by nameValueLL_setReal().
nameValueLL_addStr()
subroutine nameValueLL_data::nameValueLL_addStr (type (context_type), intent(inout) context, character(len=*), intent(in) name, character(len=*), intent(in) value, integer, intent(in) state)
Definition at line 418 of file nameValueLL_data.F90.
Referenced by nameValueLL_setStr().
nameValueLL_checkInt()
subroutine nameValueLL_data::nameValueLL_checkInt (type (int_list_type), pointer node, integer, intent(in) value, logical, intent(out) valid)
Checks if the given VALUE is valid according to rules in NODE
node: node of str_list_type value: value to be checked valid: true if valid value
Definition at line 588 of file nameValueLL_data.F90.
nameValueLL_checkReal()
subroutine nameValueLL_data::nameValueLL_checkReal (type (real_list_type), pointer node, real, intent(in) value, logical, intent(out) valid)
Checks if the given VALUE is valid according to rules in NODE
node: node of real_list_type value: value to be checked valid: true if valid value
Definition at line 544 of file nameValueLL_data.F90.
nameValueLL_checkStr()
subroutine nameValueLL_data::nameValueLL_checkStr (type (str_list_type), pointer node, character(len=*), intent(in) value, logical, intent(out) valid)
Checks if the given VALUE is valid according to rules in NODE
node: node of str_list_type value: value to be checked valid: true if valid value
Definition at line 632 of file nameValueLL_data.F90.
nameValueLL_findInt()
subroutine nameValueLL_data::nameValueLL_findInt (type (context_type), intent(in) context, character(len=*), intent(in) name, type (int_list_type), pointer result)
Definition at line 227 of file nameValueLL_data.F90.
Referenced by nameValueLL_rulesInt().
nameValueLL_findLog()
subroutine nameValueLL_data::nameValueLL_findLog (type (context_type), intent(in) context, character(len=*), intent(in) name, type (log_list_type), pointer result)
Definition at line 265 of file nameValueLL_data.F90.
nameValueLL_findReal()
subroutine nameValueLL_data::nameValueLL_findReal (type (context_type), intent(in) context, character(len=*), intent(in) name, type (real_list_type), pointer result)
Find a name in a linked list using its name. Return a pointer to the name's node if it's found, otherwise return a null pointer. This subroutine is overloaded it implements nameValueLL_findReal, nameValueLL_findInt, nameValueLL_findStr, and nameValueLL_findLog
name: name of string (in) value: name value
Definition at line 205 of file nameValueLL_data.F90.
Referenced by nameValueLL_rulesReal().
nameValueLL_findStr()
subroutine nameValueLL_data::nameValueLL_findStr (type (context_type), intent(in) context, character(len=*), intent(in) name, type (str_list_type), pointer result)
Definition at line 246 of file nameValueLL_data.F90.
Referenced by nameValueLL_rulesStr().
Variable Documentation
name_int
integer, parameter nameValueLL_data::name_int = 2
Definition at line 83 of file nameValueLL_data.F90.
name_invalid
integer, parameter nameValueLL_data::name_invalid = 0
Definition at line 83 of file nameValueLL_data.F90.
name_log
integer, parameter nameValueLL_data::name_log = 4
Definition at line 83 of file nameValueLL_data.F90.
name_real
integer, parameter nameValueLL_data::name_real = 1
Definition at line 83 of file nameValueLL_data.F90.
name_str
integer, parameter nameValueLL_data::name_str = 3
Definition at line 83 of file nameValueLL_data.F90.
NUM_MAX_RULES
integer, parameter nameValueLL_data::NUM_MAX_RULES = 10
Definition at line 28 of file nameValueLL_data.F90.
num_params
integer, save nameValueLL_data::num_params = 0
Definition at line 89 of file nameValueLL_data.F90.
TYPE_CONST
integer, parameter nameValueLL_data::TYPE_CONST = 0
Definition at line 87 of file nameValueLL_data.F90.
TYPE_VAR
integer, parameter nameValueLL_data::TYPE_VAR = 1
Definition at line 87 of file nameValueLL_data.F90.