FLASH-X: source/flashUtilities/nameValueLL/nameValueLL_rules.F90 File Reference
nameValueLL_rules.F90 File Reference
Functions/Subroutines
subroutine nameValueLL_rulesInt (context, name, numValues, minValues, maxValues)
subroutine nameValueLL_rulesReal (context, name, numValues, minValues, maxValues)
subroutine nameValueLL_rulesStr (context, name, numValues, validValues)
Function/Subroutine Documentation
nameValueLL_rulesInt()
subroutine nameValueLL_rulesInt (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer numValues, integer minValues, integer maxValues)
sets the set of valid values of "name" Runtimeparameter to validValues
context– data structure holding Runtime Parameters details name– name of parameter numValues– number of valid values minValues– array of given size, provides minimum of valid values maxValues– array of given size, provides maximum of valid values
Definition at line 27 of file nameValueLL_rules.F90.
References nameValueLL_data::nameValueLL_findInt().
nameValueLL_rulesReal()
subroutine nameValueLL_rulesReal (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer numValues, real minValues, real maxValues)
sets the set of validvalues of "name" Runtimeparameter to validValues
Arguments context: data structure holding Runtime Parameters details name: name of parameter numValues: # of valid values minValues,maxValues: array of values of given size
Definition at line 78 of file nameValueLL_rules.F90.
References nameValueLL_data::nameValueLL_findReal().
nameValueLL_rulesStr()
subroutine nameValueLL_rulesStr (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer numValues, character(len=*) validValues)
sets the set of validvalues of "name" Runtimeparameter to validValues
Arguments context: data structure holding Runtime Parameters details name: name of parameter numValues: # of valid values validValues: array of valid values of given size
Definition at line 129 of file nameValueLL_rules.F90.
References makeLowercase(), and nameValueLL_data::nameValueLL_findStr().