FLASH-X: source/flashUtilities/nameValueLL/nameValueLL_logRules.F90 File Reference
nameValueLL_logRules.F90 File Reference
Functions/Subroutines
subroutine nameValueLL_logRulesInt (name, numValues, minValues, maxValues)
subroutine nameValueLL_logRulesReal (name, numValues, minValues, maxValues)
subroutine nameValueLL_logRulesStr (name, numValues, validValues)
Function/Subroutine Documentation
nameValueLL_logRulesInt()
subroutine nameValueLL_logRulesInt (character(len=*), intent(in) name, integer numValues, integer minValues, integer maxValues)
Prints the rules for given variable in log file
name: name of parameter numValues: number of valid values minValues: array of given size, provides minimum of valid values maxValues: array of given size, provides maximum of valid values
Definition at line 26 of file nameValueLL_logRules.F90.
Referenced by nameValueLL_setInt().
nameValueLL_logRulesReal()
subroutine nameValueLL_logRulesReal (character(len=*), intent(in) name, integer numValues, real minValues, real maxValues)
Definition at line 45 of file nameValueLL_logRules.F90.
Referenced by nameValueLL_setReal().
nameValueLL_logRulesStr()
subroutine nameValueLL_logRulesStr (character(len=*), intent(in) name, integer numValues, character(len=*) validValues)
Definition at line 63 of file nameValueLL_logRules.F90.
Referenced by nameValueLL_setStr().