FLASH-X: UTPipeline Module Reference
UTPipeline Module Reference
Functions/Subroutines
subroutine UTPipeline_init (itemSize, maxItems, channelSize, comm, numChannels, procList, logUnit)
subroutine UTPipeline_initComm ()
subroutine UTPipeline_finalizeComm (doAsyncReturn)
subroutine UTPipeline_finalize
subroutine UTPipeline_progressRecvComm
subroutine utpipe_handleOldRecvMsg ()
subroutine UTPipeline_sendFullestChannel
subroutine utpipe_postSendMsg (index)
subroutine utpipe_postRecvMsg (index)
subroutine UTPipeline_progressComm (doFlush)
subroutine UTPipeline_progressSendComm ()
subroutine UTPipeline_closeSendChannels (isClosing)
subroutine utpipe_progressClosePromise ()
subroutine UTPipeline_isCommDone (isCommDone)
subroutine UTPipeline_isDone (isDone)
subroutine UTPipeline_numItems (numItems)
subroutine UTPipeline_isEmpty (isEmpty)
subroutine UTPipeline_getItems (userArray, userMaxCount, userCount)
subroutine utpipe_saveRecvItems (index, isSaved)
subroutine UTPipeline_sendItem (item, procID, isHandled)
subroutine UTPipeline_iterateItems (readOnlyFn)
subroutine Driver_checkMPIErrorCode (errorCode)
subroutine Driver_abort (msg)
Variables
integer, parameter FLASH_INTEGER = MPI_INTEGER
integer, parameter FLASH_REAL = MPI_DOUBLE_PRECISION
real, dimension(:,:,:), allocatable, save utpipe_sendBuf
real, dimension(:,:,:), allocatable, save utpipe_recvBuf
real, dimension(:,:), allocatable, save utpipe_itemBuf
integer, parameter utpipe_tag = 1235
integer, dimension(:,:), allocatable, save utpipe_recvStatus
integer, dimension(:), allocatable, save utpipe_recvRequest
integer, dimension(:), allocatable, save utpipe_recvIndex
integer, dimension(:), allocatable, save utpipe_recvCount
integer, dimension(:,:), allocatable, save utpipe_sendStatus
integer, dimension(:), allocatable, save utpipe_sendRequest
integer, dimension(:), allocatable, save utpipe_sendIndex
integer, dimension(:), allocatable, save utpipe_sendCount
integer, dimension(:), allocatable, save utpipe_procList
integer, save utpipe_itemCount
integer, save utpipe_comm
integer, save utpipe_size
integer, save utpipe_rank
integer, save utpipe_itemSize
integer, save utpipe_maxItems
integer, save utpipe_channelSize
integer, save utpipe_numChannels
logical, save utpipe_isSendCommDone
logical, save utpipe_isRecvCommDone
logical, save utpipe_isInitialized = .false.
logical, save utpipe_isCommInitialized = .false.
logical, save utpipe_isCommDone = .false.
integer, save utpipe_logUnit
logical, save utpipe_doLog
integer, dimension(:), allocatable, save utpipe_sendState
integer, parameter OPEN_STATE = -3000
integer, parameter PROMISE_TO_CLOSE_STATE = -4000
integer, parameter WAITING_TO_CLOSE_STATE = -5000
integer, parameter CLOSE_STATE = -6000
Function/Subroutine Documentation
Driver_abort()
subroutine UTPipeline::Driver_abort (character (len=*) msg)
Definition at line 657 of file UTPipeline.F90.
Driver_checkMPIErrorCode()
subroutine UTPipeline::Driver_checkMPIErrorCode (integer errorCode)
Definition at line 651 of file UTPipeline.F90.
utpipe_handleOldRecvMsg()
subroutine UTPipeline::utpipe_handleOldRecvMsg
Definition at line 276 of file UTPipeline.F90.
References utpipe_postRecvMsg(), utpipe_recvCount, utpipe_recvRequest, and utpipe_saveRecvItems().
Referenced by UTPipeline_progressRecvComm().
utpipe_postRecvMsg()
subroutine UTPipeline::utpipe_postRecvMsg (integer index)
Definition at line 340 of file UTPipeline.F90.
References utpipe_procList, utpipe_recvBuf, and utpipe_recvRequest.
Referenced by utpipe_handleOldRecvMsg(), UTPipeline_initComm(), and UTPipeline_progressRecvComm().
utpipe_postSendMsg()
subroutine UTPipeline::utpipe_postSendMsg (integer index)
Definition at line 319 of file UTPipeline.F90.
References utpipe_procList, utpipe_sendBuf, utpipe_sendCount, and utpipe_sendRequest.
Referenced by utpipe_progressClosePromise(), UTPipeline_sendFullestChannel(), and UTPipeline_sendItem().
utpipe_progressClosePromise()
subroutine UTPipeline::utpipe_progressClosePromise
Definition at line 429 of file UTPipeline.F90.
References utpipe_postSendMsg(), utpipe_sendCount, utpipe_sendRequest, and utpipe_sendState.
Referenced by UTPipeline_progressSendComm().
utpipe_saveRecvItems()
subroutine UTPipeline::utpipe_saveRecvItems (integer index, logical isSaved)
Definition at line 525 of file UTPipeline.F90.
References utpipe_itemBuf, utpipe_procList, utpipe_recvBuf, and utpipe_recvCount.
Referenced by utpipe_handleOldRecvMsg(), and UTPipeline_progressRecvComm().
UTPipeline_closeSendChannels()
subroutine UTPipeline::UTPipeline_closeSendChannels (logical isClosing)
Definition at line 412 of file UTPipeline.F90.
References utpipe_sendState, and UTPipeline_progressSendComm().
UTPipeline_finalize()
subroutine UTPipeline::UTPipeline_finalize
Definition at line 204 of file UTPipeline.F90.
References UTPipeline_finalizeComm().
UTPipeline_finalizeComm()
subroutine UTPipeline::UTPipeline_finalizeComm (logical doAsyncReturn)
Definition at line 156 of file UTPipeline.F90.
References utpipe_recvRequest, utpipe_sendRequest, and utpipe_sendState.
Referenced by UTPipeline_finalize(), and UTPipeline_isCommDone().
UTPipeline_getItems()
subroutine UTPipeline::UTPipeline_getItems (real userArray, integer userMaxCount, integer userCount)
Definition at line 492 of file UTPipeline.F90.
References utpipe_itemBuf.
UTPipeline_init()
subroutine UTPipeline::UTPipeline_init (integer itemSize, integer maxItems, integer channelSize, integer comm, integer numChannels, integer procList, integer logUnit)
Definition at line 81 of file UTPipeline.F90.
References utpipe_itemBuf, utpipe_procList, utpipe_recvBuf, utpipe_recvCount, utpipe_recvIndex, utpipe_recvRequest, utpipe_recvStatus, utpipe_sendBuf, utpipe_sendCount, utpipe_sendIndex, utpipe_sendRequest, utpipe_sendState, and utpipe_sendStatus.
UTPipeline_initComm()
subroutine UTPipeline::UTPipeline_initComm
Definition at line 129 of file UTPipeline.F90.
References utpipe_postRecvMsg(), utpipe_recvCount, utpipe_sendCount, and utpipe_sendState.
UTPipeline_isCommDone()
subroutine UTPipeline::UTPipeline_isCommDone (logical isCommDone)
Definition at line 444 of file UTPipeline.F90.
References UTPipeline_finalizeComm(), and UTPipeline_progressComm().
Referenced by UTPipeline_isDone().
UTPipeline_isDone()
subroutine UTPipeline::UTPipeline_isDone (logical isDone)
Definition at line 459 of file UTPipeline.F90.
References UTPipeline_isCommDone().
UTPipeline_isEmpty()
subroutine UTPipeline::UTPipeline_isEmpty (logical isEmpty)
Definition at line 477 of file UTPipeline.F90.
References utpipe_recvCount, and utpipe_sendCount.
UTPipeline_iterateItems()
subroutine UTPipeline::UTPipeline_iterateItems (readOnlyFn)
Definition at line 601 of file UTPipeline.F90.
References utpipe_itemBuf, utpipe_recvBuf, utpipe_recvCount, utpipe_recvRequest, utpipe_sendBuf, and utpipe_sendCount.
UTPipeline_numItems()
subroutine UTPipeline::UTPipeline_numItems (integer numItems)
Definition at line 469 of file UTPipeline.F90.
UTPipeline_progressComm()
subroutine UTPipeline::UTPipeline_progressComm (logical doFlush)
Definition at line 357 of file UTPipeline.F90.
References UTPipeline_progressRecvComm(), UTPipeline_progressSendComm(), and UTPipeline_sendFullestChannel().
Referenced by UTPipeline_isCommDone().
UTPipeline_progressRecvComm()
subroutine UTPipeline::UTPipeline_progressRecvComm
Definition at line 229 of file UTPipeline.F90.
References utpipe_handleOldRecvMsg(), utpipe_postRecvMsg(), utpipe_procList, utpipe_recvCount, utpipe_recvIndex, utpipe_recvStatus, and utpipe_saveRecvItems().
Referenced by UTPipeline_progressComm().
UTPipeline_progressSendComm()
subroutine UTPipeline::UTPipeline_progressSendComm
Definition at line 374 of file UTPipeline.F90.
References utpipe_procList, utpipe_progressClosePromise(), utpipe_sendCount, utpipe_sendIndex, and utpipe_sendState.
Referenced by UTPipeline_closeSendChannels(), UTPipeline_progressComm(), and UTPipeline_sendItem().
UTPipeline_sendFullestChannel()
subroutine UTPipeline::UTPipeline_sendFullestChannel
Definition at line 290 of file UTPipeline.F90.
References utpipe_postSendMsg(), utpipe_sendCount, utpipe_sendRequest, and utpipe_sendState.
Referenced by UTPipeline_progressComm().
UTPipeline_sendItem()
subroutine UTPipeline::UTPipeline_sendItem (real, dimension(:) item, integer procID, logical isHandled)
Definition at line 555 of file UTPipeline.F90.
References utpipe_postSendMsg(), utpipe_procList, utpipe_sendBuf, utpipe_sendCount, utpipe_sendRequest, utpipe_sendState, and UTPipeline_progressSendComm().
Variable Documentation
CLOSE_STATE
integer, parameter UTPipeline::CLOSE_STATE = -6000
Definition at line 75 of file UTPipeline.F90.
FLASH_INTEGER
integer, parameter UTPipeline::FLASH_INTEGER = MPI_INTEGER
Definition at line 28 of file UTPipeline.F90.
FLASH_REAL
integer, parameter UTPipeline::FLASH_REAL = MPI_DOUBLE_PRECISION
Definition at line 29 of file UTPipeline.F90.
OPEN_STATE
integer, parameter UTPipeline::OPEN_STATE = -3000
Definition at line 72 of file UTPipeline.F90.
PROMISE_TO_CLOSE_STATE
integer, parameter UTPipeline::PROMISE_TO_CLOSE_STATE = -4000
Definition at line 73 of file UTPipeline.F90.
utpipe_channelSize
integer, save UTPipeline::utpipe_channelSize
Definition at line 58 of file UTPipeline.F90.
utpipe_comm
integer, save UTPipeline::utpipe_comm
Definition at line 52 of file UTPipeline.F90.
utpipe_doLog
logical, save UTPipeline::utpipe_doLog
Definition at line 69 of file UTPipeline.F90.
utpipe_isCommDone
logical, save UTPipeline::utpipe_isCommDone = .false.
Definition at line 66 of file UTPipeline.F90.
utpipe_isCommInitialized
logical, save UTPipeline::utpipe_isCommInitialized = .false.
Definition at line 65 of file UTPipeline.F90.
utpipe_isInitialized
logical, save UTPipeline::utpipe_isInitialized = .false.
Definition at line 64 of file UTPipeline.F90.
utpipe_isRecvCommDone
logical, save UTPipeline::utpipe_isRecvCommDone
Definition at line 62 of file UTPipeline.F90.
utpipe_isSendCommDone
logical, save UTPipeline::utpipe_isSendCommDone
Definition at line 61 of file UTPipeline.F90.
utpipe_itemBuf
real, dimension(:,:), allocatable, save UTPipeline::utpipe_itemBuf
Definition at line 36 of file UTPipeline.F90.
Referenced by utpipe_saveRecvItems(), UTPipeline_getItems(), UTPipeline_init(), and UTPipeline_iterateItems().
utpipe_itemCount
integer, save UTPipeline::utpipe_itemCount
Definition at line 50 of file UTPipeline.F90.
utpipe_itemSize
integer, save UTPipeline::utpipe_itemSize
Definition at line 56 of file UTPipeline.F90.
utpipe_logUnit
integer, save UTPipeline::utpipe_logUnit
Definition at line 68 of file UTPipeline.F90.
utpipe_maxItems
integer, save UTPipeline::utpipe_maxItems
Definition at line 57 of file UTPipeline.F90.
utpipe_numChannels
integer, save UTPipeline::utpipe_numChannels
Definition at line 59 of file UTPipeline.F90.
utpipe_procList
integer, dimension(:), allocatable, save UTPipeline::utpipe_procList
Definition at line 49 of file UTPipeline.F90.
Referenced by utpipe_postRecvMsg(), utpipe_postSendMsg(), utpipe_saveRecvItems(), UTPipeline_init(), UTPipeline_progressRecvComm(), UTPipeline_progressSendComm(), and UTPipeline_sendItem().
utpipe_rank
integer, save UTPipeline::utpipe_rank
Definition at line 54 of file UTPipeline.F90.
utpipe_recvBuf
real, dimension(:,:,:), allocatable, save UTPipeline::utpipe_recvBuf
Definition at line 35 of file UTPipeline.F90.
Referenced by utpipe_postRecvMsg(), utpipe_saveRecvItems(), UTPipeline_init(), and UTPipeline_iterateItems().
utpipe_recvCount
integer, dimension(:), allocatable, save UTPipeline::utpipe_recvCount
Definition at line 42 of file UTPipeline.F90.
Referenced by utpipe_handleOldRecvMsg(), utpipe_saveRecvItems(), UTPipeline_init(), UTPipeline_initComm(), UTPipeline_isEmpty(), UTPipeline_iterateItems(), and UTPipeline_progressRecvComm().
utpipe_recvIndex
integer, dimension(:), allocatable, save UTPipeline::utpipe_recvIndex
Definition at line 41 of file UTPipeline.F90.
Referenced by UTPipeline_init(), and UTPipeline_progressRecvComm().
utpipe_recvRequest
integer, dimension(:), allocatable, save UTPipeline::utpipe_recvRequest
Definition at line 40 of file UTPipeline.F90.
Referenced by utpipe_handleOldRecvMsg(), utpipe_postRecvMsg(), UTPipeline_finalizeComm(), UTPipeline_init(), and UTPipeline_iterateItems().
utpipe_recvStatus
integer, dimension(:,:), allocatable, save UTPipeline::utpipe_recvStatus
Definition at line 39 of file UTPipeline.F90.
Referenced by UTPipeline_init(), and UTPipeline_progressRecvComm().
utpipe_sendBuf
real, dimension(:,:,:), allocatable, save UTPipeline::utpipe_sendBuf
Definition at line 34 of file UTPipeline.F90.
Referenced by utpipe_postSendMsg(), UTPipeline_init(), UTPipeline_iterateItems(), and UTPipeline_sendItem().
utpipe_sendCount
integer, dimension(:), allocatable, save UTPipeline::utpipe_sendCount
Definition at line 47 of file UTPipeline.F90.
Referenced by utpipe_postSendMsg(), utpipe_progressClosePromise(), UTPipeline_init(), UTPipeline_initComm(), UTPipeline_isEmpty(), UTPipeline_iterateItems(), UTPipeline_progressSendComm(), UTPipeline_sendFullestChannel(), and UTPipeline_sendItem().
utpipe_sendIndex
integer, dimension(:), allocatable, save UTPipeline::utpipe_sendIndex
Definition at line 46 of file UTPipeline.F90.
Referenced by UTPipeline_init(), and UTPipeline_progressSendComm().
utpipe_sendRequest
integer, dimension(:), allocatable, save UTPipeline::utpipe_sendRequest
Definition at line 45 of file UTPipeline.F90.
Referenced by utpipe_postSendMsg(), utpipe_progressClosePromise(), UTPipeline_finalizeComm(), UTPipeline_init(), UTPipeline_sendFullestChannel(), and UTPipeline_sendItem().
utpipe_sendState
integer, dimension(:), allocatable, save UTPipeline::utpipe_sendState
Definition at line 71 of file UTPipeline.F90.
Referenced by utpipe_progressClosePromise(), UTPipeline_closeSendChannels(), UTPipeline_finalizeComm(), UTPipeline_init(), UTPipeline_initComm(), UTPipeline_progressSendComm(), UTPipeline_sendFullestChannel(), and UTPipeline_sendItem().
utpipe_sendStatus
integer, dimension(:,:), allocatable, save UTPipeline::utpipe_sendStatus
Definition at line 44 of file UTPipeline.F90.
Referenced by UTPipeline_init().
utpipe_size
integer, save UTPipeline::utpipe_size
Definition at line 53 of file UTPipeline.F90.
utpipe_tag
integer, parameter UTPipeline::utpipe_tag = 1235
Definition at line 38 of file UTPipeline.F90.
WAITING_TO_CLOSE_STATE
integer, parameter UTPipeline::WAITING_TO_CLOSE_STATE = -5000
Definition at line 74 of file UTPipeline.F90.