FLASH-X: source/flashUtilities/nameValueLL/nameValueLL_set.F90 File Reference
nameValueLL_set.F90 File Reference
Functions/Subroutines
subroutine nameValueLL_setReal (context, name, value, current_val)
subroutine nameValueLL_setInt (context, name, value, current_val)
subroutine nameValueLL_setStr (context, name, value, current_val)
subroutine nameValueLL_setLog (context, name, value, current_val)
Function/Subroutine Documentation
nameValueLL_setInt()
subroutine nameValueLL_setInt (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer, intent(in) value, logical, intent(in) current_val)
Definition at line 98 of file nameValueLL_set.F90.
References nameValueLL_data::nameValueLL_addInt(), and nameValueLL_logRulesInt().
nameValueLL_setLog()
subroutine nameValueLL_setLog (type (context_type), intent(inout) context, character(len=*), intent(in) name, logical, intent(in) value, logical, intent(in) current_val)
Definition at line 228 of file nameValueLL_set.F90.
References nameValueLL_data::nameValueLL_addLog().
nameValueLL_setReal()
subroutine nameValueLL_setReal (type (context_type), intent(inout) context, character(len=*), intent(in) name, real, intent(in) value, logical, intent(in) current_val)
Sets real parameters into a linked list. This is an overloaded function nameValueLL_set under the hood implements nameValueLL_setReal nameValueLL_setInt, nameValueLL_setStr nameValueLL_setLog
context: structure holding all the data name: name to be set value: value of name to be set current_val: distinguishes between restart (false) and initial (true) values
Definition at line 30 of file nameValueLL_set.F90.
References nameValueLL_data::nameValueLL_addReal(), and nameValueLL_logRulesReal().
nameValueLL_setStr()
subroutine nameValueLL_setStr (type (context_type), intent(inout) context, character(len=*), intent(in) name, character(len=*), intent(in) value, logical, intent(in) current_val)
Definition at line 165 of file nameValueLL_set.F90.
References nameValueLL_data::nameValueLL_addStr(), and nameValueLL_logRulesStr().