FLASH-X: source/flashUtilities/nameValueLL/makeLowercase.F90 File Reference
makeLowercase.F90 File Reference
Functions/Subroutines
subroutine makeLowercase (str)
Function/Subroutine Documentation
makeLowercase()
subroutine makeLowercase (character(len=*) str)
Convert a string to lowercase.
str: string to be converted
Definition at line 22 of file makeLowercase.F90.
Referenced by nameValueLL_data::nameValueLL_add::nameValueLL_addInt(), nameValueLL_data::nameValueLL_add::nameValueLL_addLog(), nameValueLL_data::nameValueLL_add::nameValueLL_addReal(), nameValueLL_data::nameValueLL_add::nameValueLL_addStr(), nameValueLL_data::nameValueLL_check::nameValueLL_checkStr(), nameValueLL_data::nameValueLL_find::nameValueLL_findInt(), nameValueLL_data::nameValueLL_find::nameValueLL_findLog(), nameValueLL_data::nameValueLL_find::nameValueLL_findReal(), nameValueLL_data::nameValueLL_find::nameValueLL_findStr(), and nameValueLL_rulesStr().