FLASH-X: nameValueLL_data::nameValueLL_add Interface Reference
nameValueLL_data::nameValueLL_add Interface Reference
Public Member Functions
subroutine nameValueLL_addReal (context, name, value, state)
subroutine nameValueLL_addInt (context, name, value, state)
subroutine nameValueLL_addStr (context, name, value, state)
subroutine nameValueLL_addLog (context, name, value, state)
Detailed Description
Definition at line 108 of file nameValueLL_data.F90.
Member Function/Subroutine Documentation
nameValueLL_addInt()
subroutine nameValueLL_data::nameValueLL_add::nameValueLL_addInt (type (context_type), intent(inout) context, character(len=*), intent(in) name, integer, intent(in) value, integer, intent(in) state)
Definition at line 361 of file nameValueLL_data.F90.
References nameValueLL_data::getType(), and makeLowercase().
nameValueLL_addLog()
subroutine nameValueLL_data::nameValueLL_add::nameValueLL_addLog (type (context_type), intent(inout) context, character(len=*), intent(in) name, logical, intent(in) value, integer, intent(in) state)
Definition at line 474 of file nameValueLL_data.F90.
References nameValueLL_data::getType(), and makeLowercase().
nameValueLL_addReal()
subroutine nameValueLL_data::nameValueLL_add::nameValueLL_addReal (type (context_type), intent(inout) context, character(len=*), intent(in) name, real, intent(in) value, integer, intent(in) state)
Adds parameters to a linked list context implemented under the hood. This is an overloaded subroutine. It implements nameValueLL_addReal, nameValueLL_addInt, nameValueLL_addStr, nameValueLL_addLog
name: name value: name value
Definition at line 302 of file nameValueLL_data.F90.
References nameValueLL_data::getType(), and makeLowercase().
nameValueLL_addStr()
subroutine nameValueLL_data::nameValueLL_add::nameValueLL_addStr (type (context_type), intent(inout) context, character(len=*), intent(in) name, character(len=*), intent(in) value, integer, intent(in) state)
Definition at line 418 of file nameValueLL_data.F90.
References nameValueLL_data::getType(), and makeLowercase().
The documentation for this interface was generated from the following file:
source/flashUtilities/nameValueLL/nameValueLL_data.F90