FLASH-X: nameValueLL_data::nameValueLL_find Interface Reference
nameValueLL_data::nameValueLL_find Interface Reference
Public Member Functions
subroutine nameValueLL_findReal (context, name, result)
subroutine nameValueLL_findInt (context, name, result)
subroutine nameValueLL_findStr (context, name, result)
subroutine nameValueLL_findLog (context, name, result)
Detailed Description
Definition at line 101 of file nameValueLL_data.F90.
Member Function/Subroutine Documentation
nameValueLL_findInt()
subroutine nameValueLL_data::nameValueLL_find::nameValueLL_findInt (type (context_type), intent(in) context, character(len=*), intent(in) name, type (int_list_type), pointer result)
Definition at line 227 of file nameValueLL_data.F90.
References makeLowercase().
nameValueLL_findLog()
subroutine nameValueLL_data::nameValueLL_find::nameValueLL_findLog (type (context_type), intent(in) context, character(len=*), intent(in) name, type (log_list_type), pointer result)
Definition at line 265 of file nameValueLL_data.F90.
References makeLowercase().
nameValueLL_findReal()
subroutine nameValueLL_data::nameValueLL_find::nameValueLL_findReal (type (context_type), intent(in) context, character(len=*), intent(in) name, type (real_list_type), pointer result)
Find a name in a linked list using its name. Return a pointer to the name's node if it's found, otherwise return a null pointer. This subroutine is overloaded it implements nameValueLL_findReal, nameValueLL_findInt, nameValueLL_findStr, and nameValueLL_findLog
name: name of string (in) value: name value
Definition at line 205 of file nameValueLL_data.F90.
References makeLowercase().
nameValueLL_findStr()
subroutine nameValueLL_data::nameValueLL_find::nameValueLL_findStr (type (context_type), intent(in) context, character(len=*), intent(in) name, type (str_list_type), pointer result)
Definition at line 246 of file nameValueLL_data.F90.
References makeLowercase().
The documentation for this interface was generated from the following file:
source/flashUtilities/nameValueLL/nameValueLL_data.F90