FLASH-X: source/flashUtilities/nameValueLL/nameValueLL_getNum.F90 File Reference
nameValueLL_getNum.F90 File Reference
Functions/Subroutines
subroutine nameValueLL_getNumReal (context, num)
subroutine nameValueLL_getNumInt (context, num)
subroutine nameValueLL_getNumStr (context, num)
subroutine nameValueLL_getNumLog (context, num)
subroutine nameValueLL_getTotNum (context, num)
Function/Subroutine Documentation
nameValueLL_getNumInt()
subroutine nameValueLL_getNumInt (type (context_type), intent(in) context, integer, intent(out) num)
Definition at line 41 of file nameValueLL_getNum.F90.
Referenced by nameValueLL_getTotNum().
nameValueLL_getNumLog()
subroutine nameValueLL_getNumLog (type (context_type), intent(in) context, integer, intent(out) num)
Definition at line 68 of file nameValueLL_getNum.F90.
Referenced by nameValueLL_getTotNum().
nameValueLL_getNumReal()
subroutine nameValueLL_getNumReal (type (context_type), intent(in) context, integer, intent(out) num)
Gets the number of elements in a linked list list implemented under the hood. This subroutine is overloaded and implements nameValueLL_getNumReal, nameValueLL_getNumInt nameValueLL_getNumStr, nameValueLL_getNumLog
context: type of list (ie for parameters or scalars) num: number of elements in the list
Definition at line 27 of file nameValueLL_getNum.F90.
Referenced by nameValueLL_getTotNum().
nameValueLL_getNumStr()
subroutine nameValueLL_getNumStr (type (context_type), intent(in) context, integer, intent(out) num)
Definition at line 54 of file nameValueLL_getNum.F90.
Referenced by nameValueLL_getTotNum().
nameValueLL_getTotNum()
subroutine nameValueLL_getTotNum (type (context_type), intent(in) context, integer, intent(out) num)
Definition at line 82 of file nameValueLL_getNum.F90.
References nameValueLL_getNumInt(), nameValueLL_getNumLog(), nameValueLL_getNumReal(), and nameValueLL_getNumStr().