name: build-docs

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  create:
    name: "ubuntu" 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Build test environment
      run: |
          sudo apt-get update -y
          sudo apt-get install python3-pip python3-dev python3-setuptools apache2 -y
          pip3 install --upgrade pip
          pip3 install sphinx
          pip3 install sphinx-rtd-theme
    - name: Run test
      run: |
          cd sphinx && make html
